# Generated by Django 4.2.7 on 2023-11-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_personalmessage_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='personalmessage',
            name='dest_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_user_personal_messages', to='chat.profile'),
        ),
        migrations.AlterField(
            model_name='personalmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_personal_messages', to='chat.profile'),
        ),
        migrations.AlterField(
            model_name='roommessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
