# Generated by Django 4.2.7 on 2023-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile_alter_personalmessage_dest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_category',
            field=models.CharField(choices=[('NONE', 'None'), ('USER', 'User'), ('ROOM', 'Room')], default='NONE', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_chat',
            field=models.IntegerField(default=-1),
        ),
    ]
