# Generated by Django 4.2.7 on 2023-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
